### ISSUE TITLE
If you keep it running too long..

### ISSUE THREAD

**Issue by tomdevdev** [lsjwzh/MaterialLoadingProgressBar#2]
If you keep it running too long, it breaks. I left it running in the emulator(for hours I guess), and now the circle stays filled for a few seconds on every spin.

![2015-02-17 17_11_05-5554_nexus_one_api_21](https://cloud.githubusercontent.com/assets/11042257/6231779/0ae64b5e-b6c8-11e4-8f09-cebbe8c5aa29.png)

**Comment by lsjwzh** [comment]
Thanks for your feedback.
I am tracing this problem.It may be caused by  `EndCurveInterpolator` and `StartCurveInterpolator`.
As you know, the span angle is produced  by "startAngle - endAngle",but when the app running too long,
`EndCurveInterpolator` and `StartCurveInterpolator` will make a offset larger than 360 degree.That is why  the circle stays filled for a few seconds.
I have fixed it at verison 0.4.
